# This is a basic workflow to help you get started with Actions

name: publish-html-files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      # install the python needed
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 

      # install dependencies to run jupyter nbconvert
      - name: install dependencies
        run: python -m pip install --upgrade pip -r resources/requirements.txt

      # nbconvert to create html from the ipynb files
      - name: run nbconvert
        run: |
          for nb in $(ls *.ipynb)
             do jupyter nbconvert --to html $nb
          done
          mkdir notebooks-html/
          if ls *.html >/dev/null 2>&1; then
             mv *.html notebooks-html/
          fi
          
          for dir in */; do
            # Check if it's a directory (excluding symbolic links)
            if [ -d "$dir" ] && ! [ -L "$dir" ]; then
              if ls "$dir"/*.ipynb >/dev/null 2>&1; then
                for nb in $(ls $dir/*.ipynb)
                  do jupyter nbconvert --to html $nb
                done
                mkdir notebooks-html/$dir/
                mv $dir/*.html notebooks-html/$dir/
              fi
            fi
          done

      # create the index page for gh-pages
      - name: create index
        run: python resources/create_notebooks_index.py resources/config.yaml  > notebooks-html/index.html 

      # deploy the html pages to the gh-pages branch
      - name: deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: notebooks-html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

